# Generated by Django 4.1.3 on 2022-11-12 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0009_alter_share_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='likes',
            field=models.ManyToManyField(related_name='share_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
